{{- if (eq .Values.saleor.jobs.init.currencyUpdates.enabled true) }}
---
{{- $thisJob := .Values.saleor.jobs.init.currencyUpdates }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "saleor.fullname" . }}-currency-updates
  labels:
    app: {{ template "saleor.name" . }}
    chart: {{ template "saleor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": {{ (default 4 $thisJob.weight) | quote }}
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  activeDeadlineSeconds: {{ default 300 $thisJob.activeDeadlineSeconds }}
  ttlSecondsAfterFinished: {{ default 240 $thisJob.ttlSecondsAfterFinished }}
  backoffLimit: {{ default 10 $thisJob.backOffLimit }}
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: {{ template "saleor.fullname" . }}-currency-updates
      labels:
        app: {{ template "saleor.name" . }}
        chart: {{ template "saleor.chart" . }}
        release: {{ .Release.Name }}
    spec:
    {{- if .Values.saleor.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.saleor.image.pullSecret }}
    {{- end }}
      volumes:
        - name: custom-settings
          configMap:
          {{- if (not .Values.saleor.django.alternativeSettingsConfigMap) }}
            name: {{ template "saleor.fullname" . }}-custom-settings
          {{- else }}
            name: {{ .Values.saleor.django.alternativeSettingsConfigMap }}
          {{- end }}
      restartPolicy: OnFailure
      containers:
        - name: {{ template "saleor.fullname" . }}-currency-updates
          image: "{{ .Values.saleor.image.repository }}:{{ .Values.saleor.image.tag }}"
          imagePullPolicy: {{ .Values.saleor.image.pullPolicy }}
          command:
            - python3
            - manage.py
            - update_exchange_rates
            - --all
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
{{- include "saleor.standardEnv" . | indent 10 }}
          volumeMounts:
            - name: custom-settings
              mountPath: /app/saleor/custom-settings.py
              subPath: custom-settings.py
              readOnly: true
{{- end -}}
