---
jobs:
  include:
    - &docker_prepare
      stage: "docker build test"
      env:
        - DOCKERHUB_USERNAME=smoloney
        - DOCKERHUB_REPO=saleor
        - DOCKERHUB_URL="${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}"
        - SALEOR_BRANCH=master
      language: bash
      before_script:
       - |
        git clone https://github.com/mirumee/saleor.git --branch=${SALEOR_BRANCH} && cd saleor &&
        export LATEST_SALEOR_TAG=$(git rev-parse --short $(git rev-parse HEAD)) &&
        export RECENTLY_BUILT_IMAGES=$(curl --silent https://hub.docker.com/v2/repositories/${DOCKERHUB_URL}/tags/  | jq '.results | .[] | .name') &&
        if [[ ${RECENTLY_BUILT_IMAGES} != "" && ${RECENTLY_BUILT_IMAGES} == *"${LATEST_SALEOR_TAG}"* ]]; then
          export SKIP=true;
        fi &&
        if [[ -z ${SKIP} ]]; then
          cp ../Dockerfile ./
        fi
      script:
       - |
          docker build . &&
          docker run --rm ${DOCKERHUB_URL}:latest /bin/bash -c 'echo "build ok"'

    - <<: *docker_prepare
      stage: "docker image push"
      if: |
        branch = master
      script:
       - |
          if [[ -z ${SKIP} ]]; then
            echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
            docker build --tag ${DOCKERHUB_URL}:latest . &&
            docker tag ${DOCKERHUB_URL}:latest ${DOCKERHUB_URL}:${SALEOR_BRANCH}-${LATEST_SALEOR_TAG} &&
            docker push ${DOCKERHUB_URL}:latest && docker push ${DOCKERHUB_URL}:${SALEOR_BRANCH}-${LATEST_SALEOR_TAG}
          fi
