{{- if (eq .Values.saleor.jobs.cron.currencyUpdates.enabled true) }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "saleor.fullname" . }}-currency-updates-cron
spec:
  schedule: {{ .Values.saleor.jobs.cron.currencyUpdates.cron | quote }}
  jobTemplate:
    spec:
      template:
        spec:
        {{- if .Values.saleor.image.pullSecret }}
          imagePullSecrets:
            - name: {{ .Values.saleor.image.pullSecret }}
        {{- end }}
          volumes:
            - name: custom-settings
              configMap:
              {{- if (not .Values.saleor.django.alternativeSettingsConfigMap) }}
                name: {{ template "saleor.fullname" . }}-custom-settings
              {{- else }}
                name: {{ .Values.saleor.django.alternativeSettingsConfigMap }}
              {{- end }}
          restartPolicy: OnFailure
          containers:
            - name: {{ template "saleor.fullname" . }}-currency-updates-cron
              image: "{{ .Values.saleor.image.repository }}:{{ .Values.saleor.image.tag }}"
              imagePullPolicy: {{ .Values.saleor.image.pullPolicy }}
              command:
                - python3
                - manage.py
                - update_exchange_rates
                - --all
{{- include "saleor.standardEnv" . | indent 14 }}
              securityContext:
                runAsNonRoot: true
                runAsUser: 1001
              volumeMounts:
                - name: custom-settings
                  mountPath: /app/saleor/custom-settings.py
                  subPath: custom-settings.py
                  readOnly: true
{{- end -}}
